server:
  port: 8230
spring:
  ai:
    openai:
      # TODO: 上线更新环境变量
      api-key:
      base-url:
      chat:
        options:
          model: deepseek-chat
          temperature: 0.7
          max-tokens: 120
